/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_consultas;

/**
 *
 * @author Scooter
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    public VentanaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Todo = new javax.swing.JTabbedPane();
        Equipos = new javax.swing.JTabbedPane();
        ConsultaEquipo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EC_Serial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tfEC_Equipo = new javax.swing.JTextField();
        sC_Editar = new javax.swing.JToggleButton();
        tfEC_Marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbnC = new javax.swing.JButton();
        AgregarEquipo = new javax.swing.JPanel();
        Calibraciones = new javax.swing.JTabbedPane();
        VentanaConsulta_A1 = new javax.swing.JTabbedPane();
        VentanaAgregar1 = new javax.swing.JTabbedPane();
        Mantenimientos = new javax.swing.JTabbedPane();
        VentanaConsulta_A2 = new javax.swing.JTabbedPane();
        VentanaAgregar2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Todo.setBackground(new java.awt.Color(23, 55, 83));
        Todo.setForeground(new java.awt.Color(255, 255, 255));

        Equipos.setBackground(new java.awt.Color(29, 138, 153));
        Equipos.setForeground(new java.awt.Color(255, 255, 255));

        ConsultaEquipo.setBackground(new java.awt.Color(199, 235, 240));
        ConsultaEquipo.setForeground(new java.awt.Color(199, 235, 240));

        jLabel1.setText("Serial del equipo:");

        jTable1.setBackground(new java.awt.Color(247, 181, 56));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Equipo:");

        sC_Editar.setText("Editar");
        sC_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sC_EditarActionPerformed(evt);
            }
        });

        jLabel3.setText("Marca:");

        tbnC.setText("Buscar");

        javax.swing.GroupLayout ConsultaEquipoLayout = new javax.swing.GroupLayout(ConsultaEquipo);
        ConsultaEquipo.setLayout(ConsultaEquipoLayout);
        ConsultaEquipoLayout.setHorizontalGroup(
            ConsultaEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaEquipoLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(ConsultaEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConsultaEquipoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfEC_Marca, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(tfEC_Equipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sC_Editar)
                .addGap(152, 152, 152))
            .addGroup(ConsultaEquipoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EC_Serial, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbnC)
                .addGap(107, 107, 107))
            .addGroup(ConsultaEquipoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        ConsultaEquipoLayout.setVerticalGroup(
            ConsultaEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaEquipoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ConsultaEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(EC_Serial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnC))
                .addGap(18, 18, 18)
                .addGroup(ConsultaEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfEC_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sC_Editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEC_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        Equipos.addTab("Consultar", ConsultaEquipo);

        AgregarEquipo.setBackground(new java.awt.Color(199, 235, 240));

        javax.swing.GroupLayout AgregarEquipoLayout = new javax.swing.GroupLayout(AgregarEquipo);
        AgregarEquipo.setLayout(AgregarEquipoLayout);
        AgregarEquipoLayout.setHorizontalGroup(
            AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        AgregarEquipoLayout.setVerticalGroup(
            AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        Equipos.addTab("Agregar", AgregarEquipo);

        Todo.addTab("Equipos", Equipos);
        Equipos.getAccessibleContext().setAccessibleName("ConsultaA");

        Calibraciones.addTab("Consultar", VentanaConsulta_A1);
        Calibraciones.addTab("Agregar", VentanaAgregar1);

        Todo.addTab("Calibraciones", Calibraciones);
        Calibraciones.getAccessibleContext().setAccessibleName("");

        Mantenimientos.addTab("Consultar", VentanaConsulta_A2);
        Mantenimientos.addTab("Agregar", VentanaAgregar2);

        Todo.addTab("Mantenimientos", Mantenimientos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Todo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Todo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sC_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sC_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sC_EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarEquipo;
    private javax.swing.JTabbedPane Calibraciones;
    private javax.swing.JPanel ConsultaEquipo;
    private javax.swing.JTextField EC_Serial;
    private javax.swing.JTabbedPane Equipos;
    private javax.swing.JTabbedPane Mantenimientos;
    private javax.swing.JTabbedPane Todo;
    private javax.swing.JTabbedPane VentanaAgregar1;
    private javax.swing.JTabbedPane VentanaAgregar2;
    private javax.swing.JTabbedPane VentanaConsulta_A1;
    private javax.swing.JTabbedPane VentanaConsulta_A2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton sC_Editar;
    private javax.swing.JButton tbnC;
    private javax.swing.JTextField tfEC_Equipo;
    private javax.swing.JTextField tfEC_Marca;
    // End of variables declaration//GEN-END:variables
}
